name: qvid
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  video_player: ^2.1.1
  carousel_slider: ^4.0.0-nullsafety.0
  google_fonts: ^2.1.0
  flutter_bloc: ^7.0.0
  flutter_staggered_grid_view: ^0.3.3
  font_awesome_flutter: ^9.1.0
  image_picker: ^0.8.4+1
  share: ^2.0.4
  animation_wrappers: ^0.0.4
  pin_code_fields: ^7.3.0 
  http: ^0.13.3
  fluttertoast: ^8.0.8
  future_progress_dialog: ^0.2.0
  convert: ^3.0.1
  shared_preferences: ^2.0.8
  file_picker: ^3.0.1
  camera: ^0.9.4+1
  video_trimmer: ^0.6.0
  assets_audio_player: ^3.0.3+1
  path_provider: ^2.0.5
  video_compress: ^3.1.0
  percent_indicator: ^3.0.1
  tapioca: ^1.0.5+1
  flash: ^2.0.3
  http_parser: ^4.0.0
  video_thumbnail: ^0.4.3
  shimmer: ^2.0.0
  cached_network_image: ^3.1.0
  flutter_spinkit: ^5.1.0
  lottie: ^1.2.1 
  flutter_keyboard_visibility: ^5.1.0
  flutter_switch: ^0.3.2
  dropdown_search: ^1.0.4
  flutter_beautiful_popup: ^1.5.0
  image_cropper: ^1.4.1
  flutter_image_compress: ^1.1.0
  firebase_messaging: ^11.2.0 
  url_launcher: ^6.0.12
  firebase_core: "^1.10.2"
  flutter_local_notifications: ^9.1.4
  get: ^4.5.1
  audio_video_progress_bar: ^0.10.0
  flick_video_player: ^0.3.1
  google_sign_in: ^5.2.1
  firebase_auth: ^3.3.4
  chewie: ^1.2.2
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.9.2"
  flutter_app_name: ^0.1.1
  

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/logo/logo.png" 
flutter_app_name:
  name: "Clap"

flutter:

  uses-material-design: true
  assets:
    
    - assets/images/
    - assets/audio/
    - assets/icons/
    - assets/user/
    - assets/logo/
    - assets/thumbnails/dance/
    - assets/thumbnails/lol/
    - assets/thumbnails/food/
    - assets/animation/

splash_screen_view:
  # Use color to set the background of your splash screen to a solid color.
  # Use background_image to set the background of your splash screen to a png image.
  # This is useful for gradients. The image will be stretch to the  size of the app.
  # Only one parameter can be used, color and background_image cannot both be set.

  #color: "#18181A"
  #background_image: "assets/splashscreen_image.png"

  # Optional parameters are listed below.
  #image: assets/logo/logo.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  # android: true
  # ios: true
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  #fullscreen: true
  flutter:
  fonts:
    - family: Times
      fonts:
        - asset: fonts/times.ttf
    - family: Roboto
      fonts:
        - asset: fonts/roboto.ttf
    - family: RobotoSlab
      fonts:
        - asset: fonts/robotoslab.ttf
        
        
    
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'`